language: node_js
node_js:
  - "8.9"
sudo: false
cache:
  directories:
    - node_modules
before_install:
#brew tap srcclr/srcclr
#brew install srcclr
#srcclr activate
#srcclr scan --url https://github.com/srcclr/example-javascript-yarn
# Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"

  # Remove all non-test dependencies
  - "npm rm --save-dev connect-redis"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
 # - "npm tap srcclr/srcclr"
  - "npm install srcclr"
script:
  - "srcclr activate"
  - "srcclr scan --url https://github.com/srcclr/example-javascript-yarn"

#after_success:
 # - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scripts/ff-start-travis.sh)
after_success:
- bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --blackduck.hub.url="https://hubeval32.blackducksoftware.com" --blackduck.hub.username="ntu" --blackduck.hub.password="ntu@2018" --blackduck.hub.trust.cert=true --detect.policy.check=true
